---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: bert-e-config
  files:
  - settings.yml
- name: bert-e-env
  envs:
  - secrets.env

configMapGenerator:
- name: bert-e-env
  envs:
    - bert-e.env

images:
- name: bert-e
  newName: 'ghcr.io/bert-e'
  newTag: '3.6.23'

resources:
- deployment.yaml
- service.yaml

