# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: python:2.7

pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - flake8 *.py
          - coverage run test_webhook_listener.py
          - coverage run test_wall_e.py --failfast -v dummy_pwd dummy_pwd rayene_benrayana another_user_pass another_user@scality.com
          - coverage report
          - coverage html
  development/1.0:
    - step:
        script:
          - echo $DOCKER_HOST1_ENV_TAR_GZ_BASE64 | base64 --decode | tar -zxvf -
          - . env
          - curl -sSL https://get.docker.com/ | sh
          - ./deploy.sh wall_e_development_1_0 5001
  release/1.0:
    - step:
        script:
          - echo $DOCKER_HOST1_ENV_TAR_GZ_BASE64 | base64 --decode | tar -zxvf -
          - . env
          - curl -sSL https://get.docker.com/ | sh
          - ./deploy.sh wall_e_release_1_0 5000
