codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    after_n_builds: 15
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 80%
