# repository_host [MANDATORY]:
#   The git hosting provider for the repository. Either bitbucket or github.
repository_host: bitbucket

# repository_owner [MANDATORY]:
#   The name of the owner of the Bitbucket/GitHub repository to work on
#
#   (a.k.a. Bitbucket team or GitHub organization)
#
repository_owner: my_company


# repository_slug [MANDATORY]:
#   The slug of the Bitbucket/GitHub repository to work on
#
repository_slug: my_repository


# robot_username [MANDATORY]:
#   The Bitbucket/GitHub account to use for interactions with pull requests
#
#   This user will act as the robot and will:
#   - comment pull requests to indicate the progress of the merge,
#   - merge feature branches to development/* branches.
#
#   The user must have the correct permissions in Bitbucket/GitHub
#   to allow those operations (it is typically the only user allowed
#   to merge to development/* branches).
#
#   The password associated to the account is passed on the command line.
#
robot_username: robot_username


# robot_email [MANDATORY]:
#   The email address of the robot
#
#   This email will be referenced in the Git merge commits created
#   by the robot.
#
robot_email: nobody@nowhere.com


# pull_request_base_url [MANDATORY]:
#   The PR base url to link in status page
#
pull_request_base_url: https://bitbucket.org/foo/bar/pull-requests/{pr_id}


# commit_base_url [MANDATORY]:
#   The commit base url to link in status page
#
commit_base_url: https://bitbucket.org/foo/bar/commits/{commit_id}


# build_key [OPTIONAL]:
#   The label of the key to look for in bitbucket commit statuses.
#
#   default value: pre-merge
#
build_key: pre-merge


# required_peer_approvals [OPTIONAL]:
#   Number of approvals required in the pull-request in addition to author.
#
#   values: 0 or more
#   default value: 2
#
required_peer_approvals: 2


# jira_account_url [OPTIONAL]:
#   The url of the Jira account.
#
#   empty: no Jira checks will be performed.
#
jira_account_url: https://my_account.atlassian.net


# jira_username [OPTIONAL]:
#   The login to use to retrieve information from Jira.
#
#   empty: no Jira checks will be performed.
#
jira_username: my_jira_username


# jira_keys [OPTIONAL]:
#   The list of accepted Jira keys for this project.
#
#   values: list of accepted keys
#   default value: empty
#   empty: no Jira checks will be performed.
#
jira_keys:
  - MYJIRAPROJECTKEY


# prefixes [OPTIONAL]:
#   The dictionnary of expected match between the Jira issue type
#   and branch prefix.
#
#   default value: empty
#   empty: the branch prefix is not checked.
#
prefixes:
  Story: feature
  Bug: bugfix
  Improvement: improvement


# admins [OPTIONAL]:
#   The list of bitbucket accounts allowed to post privileged messages
#   to the bot
#
#   default value: empty
#   empty: no one can post privileged messages
#
admins:
  - username_admin_1
  - username_admin_2


# tasks [OPTIONAL]:
#   The list of tasks to create by default on the bitbucket pull request
#
#   default value: empty
#   empty: no task is created by default
tasks:
  - do this
  - do that
