---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" $ }}-env
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  BERT_E_GITHOST_PWD: {{ .Values.bertE.robot.password | b64enc | quote }}
  WEBHOOK_LOGIN: {{ .Values.bertE.webhook.username | b64enc | quote }}
  WEBHOOK_PWD: {{ .Values.bertE.webhook.password | b64enc | quote }}
  BERT_E_JIRA_TOKEN: {{ .Values.bertE.jira.token | b64enc | quote }}
  BERT_E_CLIENT_ID: {{ .Values.bertE.oauth.clientId | b64enc | quote }}
  BERT_E_CLIENT_SECRET: {{ .Values.bertE.oauth.clientSecret | b64enc | quote }}
