---
branches:
  feature/*:
    stage: tests
  bugfix/*:
    stage: tests
  improvement/*:
    stage: tests

stages:
  tests:
    worker:
      type: docker
      path: eve/ubuntu-trusty
    steps:
      - Git:
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: linting with flake8
          command: flake8 *.py
      - ShellCommand:
          name: launch Wall-E tests
          command: python test_wall_e.py
                     -v
                     --repo-prefix _test_wall_e_eve
                     foo
                     bar
                     sylvain_killian
                     foo
                     sylvain.killian@scality.com
