---
version: 0.1

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: docker
      path: eve/ubuntu-xenial
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: ok command
          command: echo "toto"
      - ShellCommand:
          name: no ok
          command: exit 1
          haltOnFailure: False
          flunkOnFailure: True
