---
version: 0.1

branches:
  feature/*, bugfix/*, improvement/*, w/*:
    stage: tests

stages:
  tests:
    worker:
      type: docker
      path: eve/ubuntu-xenial
    steps:
      - Git:
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: flake8
          command: flake8 *.py
      - ShellCommand:
          name: Esteban tests
          command: coverage run -a test_esteban.py
      - ShellCommand:
          name: Wall-E tests
          command: coverage run -a test_wall_e.py
                     -v
                     --repo-prefix _test_wall_e_eve
                     foo
                     bar
                     sylvain_killian
                     foo
                     sylvain.killian@scality.com
      - ShellCommand:
          name: Coverage report
          command: coverage report *.py
