---
version: 0.2

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: local
    steps:
      - ShellCommand:
          name: MyStep
          command: echo 1
      - ShellCommand:
          name: MyStep
          command: echo 2
      - ShellCommand:
          name: MyStep
          command: echo 3
      - ShellCommand:
          name: MyStep
          command: echo 4
