---
version: 0.1

branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: local
    steps:
    - TriggerStages:
        name: Syntax checker
        haltOnFailure: true
        stage_names:
        - lint
    - TriggerStages:
        name: trigger all the tests
        haltOnFailure: true
        stage_names:
        - tests
  lint:
    worker:
      type: kube_pod
      path: eve/worker/worker.yaml
      images:
        worker: eve/worker/dockerfile
    steps:
    - Git: &git_pull
        name: git pull
        repourl: "%(prop:git_reference)s"
        shallow: True
        retryFetch: True
        haltOnFailure: True
    - ShellCommand:
        name: 'flake8'
        haltOnFailure: true
        command: tox -e flake8
    - ShellCommand:
        name: 'check helm packaging'
        command: helm lint charts/bert-e
        haltOnFailure: true

  tests:
    worker:
      type: kube_pod
      path: eve/worker/worker.yaml
      images:
        worker: eve/worker/dockerfile
    steps:
    - Git: *git_pull
    - ShellCommand:
        name: unit tests
        command: tox -e utests
    - ShellCommand:
        name: Git host API mock tests
        command: tox -e tests-api-mock
    - ShellCommand:
        name: Bert-E server tests
        command: tox -e tests-server
    - ShellCommand:
        name: Bert-E tests (no queue support)
        command: tox -e tests-noqueue
    - ShellCommand:
        name: Bert-E tests (with queue support)
        command: tox -e tests
    - ShellCommand:
        name: Coverage report
        command: tox -e coverage-report
