---
branches:
  feature/*, bugfix/*, improvement/*, w/*, q/*:
    stage: tests

stages:
  tests:
    worker:
      type: docker
      path: eve/ubuntu-xenial
    steps:
      - Git:
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: flake8
          command: flake8 *.py
      - ShellCommand:
          name: Esteban tests
          command: coverage run -a test_esteban.py
      - ShellCommand:
          name: Wall-E tests (no queue support)
          command: coverage run -a test_wall_e.py
                     -v
                     --repo-prefix _test_wall_e_eve
                     --disable-queues
                     mock_owner
                     mock_robot_username
                     mock_robot_password
                     mock_user_username
                     mock_user_password
                     mock_admin_username
                     mock_admin_password
      - ShellCommand:
          name: Wall-E tests with queue support
          command: coverage run -a test_wall_e.py
                     -v
                     --repo-prefix _test_wall_e_eve
                     mock_owner
                     mock_robot_username
                     mock_robot_password
                     mock_user_username
                     mock_user_password
                     mock_admin_username
                     mock_admin_password
      - ShellCommand:
          name: Coverage report
          command: coverage report *.py
