---
name: build

on: push

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/scality/bert-e:${{ github.sha }}
          cache-from: type=gha,scope=bert-e
          cache-to: type=gha,mode=max,scope=bert-e

  scan:
    needs: build
    uses: ./.github/actions/trivy.yaml
