---
name: build

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  schedule:
  # Run once a week at 00:00 on Sunday
  - cron: '0 0 * * 0'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/scality/bert-e:${{ github.sha }}
          cache-from: type=gha,scope=bert-e
          cache-to: type=gha,mode=max,scope=bert-e

  scan:
    needs: build
    uses: ./.github/workflows/trivy.yaml
    with:
      image: ghcr.io/scality/bert-e:${{ github.sha }}
