---

name: containersec

on: push

jobs:
  # A job that will use actions/github-script get all releases and output them
  releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.releases }}
    steps:
      - name: Get all releases
        id: releases
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            // Set an output release containing all  the tag names and the according commit
            core.setOutput('releases', releases.data.map(release => {
              return {
                tag_name: release.tag_name,
                sha: release.target_commitish
              }
            }))
            return releases.data.map(release => release.tag_name)
      - name: Output all releases
        run: |
          echo "All releases: ${{ steps.releases.outputs.result }}"
          echo "All releases: ${{ steps.releases.outputs.releases }}"
  analyse:
    name: analyse
    runs-on: ubuntu-latest
    needs: releases
    strategy:
      matrix:
        releases: ${{ fromJson(needs.releases.outputs.releases) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.releases.tag_name }}
          # pull all commits
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "registry.scality.com/bert-e/bert-e:${{ matrix.releases.tag_name }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
        env:
          TRIVY_USERNAME: ${{ secrets.REGISTRY_LOGIN }}
          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        continue-on-error: true

      # In order to specify the ref and sha in which trivy
      # ran the analysis, the action codeql-action/upload-sarif@v2
      # must be set with the following parameters:
      # ref: ${{ matrix.releases.tag_name }}
      # commit: ${{ matrix.releases.sha }}
      # The following step is a workaround to set the ref and sha
      # in the sarif file.

      - name: Set ref and sha in sarif file
        run: |
          sed -i "s|\"ref\": null|\"ref\": \"${{ matrix.releases.tag_name }}\"|g" trivy-results.sarif
          sed -i "s|\"commit\": null|\"commit\": \"${{ matrix.releases.sha }}\"|g" trivy-results.sarif
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        # execute step on if previous step was successful
        if: ${{ success() }}
        with:
          sarif_file: 'trivy-results.sarif'
          ref: refs/tags/${{ matrix.releases.tag_name }}
          sha: ${{ matrix.releases.sha }}
