---

name: containersec

on:
  push:
    branches: [ '**' ]
  schedule:
  # Every day at noon
  - cron: '0 12 * * *'
  workflow_call:
    inputs:
      image:
        description: 'Image to scan'
        required: false
        type: string
        default: 'ghcr.io/scality/bert-e'
      ref:
        description: |
          The branch or tag to scan. If not specified, the default branch is used.
        required: false
        type: string
        default: '${{ github.ref }}'
      sha:
        description: 'SHA to scan'
        required: false
        type: string
        default: '${{ github.sha }}'
      ref_type:
        description: 'Type of ref to scan'
        required: false
        type: string
        default: '${{ github.ref_type }}'

jobs:
  scan-image:
    name: analyse
    runs-on: ubuntu-latest
    needs: releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ inputs.image }}:${{ inputs.ref }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          ref: 'refs/${{ inputs.ref_type }}/${{ inputs.ref }}'
          sha: ${{ inputs.sha }}
