name: basic tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'dependabot/**'
      - 'w/**'
      - 'q/**'

permissions: write-all

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Boot compose test service
        run: docker compose up --build --detach
        working-directory: bert_e/tests/images
      - name: Install tox
        run: pip install tox
      - run: tox -e utests
      - run: tox -e tests-api-mock
      - run: tox -e coverage-report
      - run: tox -e tests-server
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          flags: unittests,server,api-mock

  tests-noqueue:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install tox
        run: pip install tox
      - run: tox -e tests-noqueue
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          flags: tests-noqueue

  all-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install tox
        run: pip install tox
      - run: tox -e tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          flags: all-tests

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install tox
        run: pip install tox
      - run: tox -e flake8
      - run: helm lint charts/bert-e
