name: basic tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'w/**'
      - 'q/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: eve/worker/dockerfile
          file: eve/worker/dockerfile/actions.Dockerfile
          build-args: BUILDBOT_VERSION=2.0.1
          tags: "ghcr.io/scality/bert-e:${{ github.sha }}"

  tests:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: tox -e utests
      - run: tox -e tests-api-mock
      - run: tox -e tests-noqueue
      - run: tox -e tests
      - run: tox -e coverage-report
      - run: tox -e tests-server


  lint:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -la /__w/bert-e/bert-e/
      - run: bash -c "cd /home/eve/workspace && ls -la"
      - run: tox -e flake8
      - run: helm lint charts/bert-e