name: basic tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: write-all

jobs:
  unit:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        test:
          - utests
          - tests-api-mock
          - tests-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Boot compose test service
        run: docker compose up --build --detach
        working-directory: bert_e/tests/images
      - name: Install tox
        run: pip install tox
      - run: tox -e ${{ matrix.test }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          flags: unittests, ${{ matrix.test }}

  integration:
    strategy:
      matrix:
        test:
          - tests-noqueue
          - tests
        class:
          - QuickTest
          - BuildFailedTest
          - RepositoryTests
          - TestBertE
          - TestQueueing
          - TaskQueueTests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install tox
        run: pip install tox
      - run: tox -e ${{ matrix.test }} -- ${{ matrix.class }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          flags: integration, ${{ matrix.test }}, ${{ matrix.test }}-${{ matrix.class }}

  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install tox
        run: pip install tox
      - run: tox -e flake8
      - run: helm lint charts/bert-e
