name: basic tests

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'dependabot/**'
      - 'w/**'
      - 'q/**'

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildk
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .github/docker
          file: .github/docker/Dockerfile
          tags: "ghcr.io/scality/bert-e:${{ github.sha }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  tests:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --global --add safe.directory /__w/bert-e/bert-e
      - run: tox -e utests
      - run: tox -e tests-api-mock
      - run: tox -e coverage-report
      - run: tox -e tests-server

  tests-noqueue:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --global --add safe.directory /__w/bert-e/bert-e
      - run: tox -e tests-noqueue

  all-tests:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --global --add safe.directory /__w/bert-e/bert-e
      - run: tox -e tests

  lint:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scality/bert-e:${{ github.sha }}"
      options: --user=0
    needs:
      - publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git config --global --add safe.directory /__w/bert-e/bert-e
      - run: tox -e flake8
      - run: helm lint charts/bert-e
