---

name: containersec

on:
  push:
    branches: [ development/* ]
  schedule:
  # Every day at noon
  - cron: '0 12 * * *'
  workflow_dispatch: {}


jobs:
  # A job that will use actions/github-script get all releases and output them
  releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.releases }}
    steps:
      - name: Get all releases
        id: releases
        uses: actions/github-script@v6
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            // Set an output release containing all  the tag names and the according commit
            core.setOutput('releases', releases.data.map(release => {
              return {
                tag_name: release.tag_name,
                sha: release.target_commitish
              }
            }))
            return releases.data.map(release => release.tag_name)
      - name: Output all releases
        run: |
          echo "All releases: ${{ steps.releases.outputs.result }}"
          echo "All releases: ${{ steps.releases.outputs.releases }}"
  analyse:
    name: analyse
    needs: releases
    strategy:
      matrix:
        releases: ${{ fromJson(needs.releases.outputs.releases) }}
      fail-fast: false
    uses: ./.github/workflows/trivy.yaml
    with:
      image: 'registry.scality.com/bert-e/bert-e'
      ref: ${{ matrix.releases.tag_name }}
      sha: ${{ matrix.releases.sha }}
      ref_type: 'tag'