---

name: trivy

on:
  schedule:
  # Every day at noon
  - cron: '0 12 * * *'
  workflow_call:
    inputs:
      image:
        description: 'Image to scan'
        required: false
        type: string
      ref:
        description: |
          The branch or tag to scan. If not specified, the default branch is used.
        required: false
        type: string
      sha:
        description: 'Scanned git SHA'
        required: false
        type: string
      ref_type:
        description: 'Type of ref to scan'
        required: false
        type: string

env:
  IMAGE: ${{ inputs.image || 'ghcr.io/scality/bert-e' }}
  REF: ${{ inputs.ref || github.sha }}
  SHA: ${{ inputs.sha || github.sha }}
  REF_TYPE: ${{ inputs.ref_type || github.ref_type }}

jobs:
  analyse:
    name: analyse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE }}:${{ env.REF }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          ref: 'refs/${{ env.REF_TYPE }}/${{ env.REF }}'
          sha: ${{ env.SHA }}
